from book.models import Ingredient
from django.core.management.base import BaseCommand
from django.conf import settings
import os

class Command(BaseCommand):
    help = 'Generate an ingredients'

    def handle(self, *args, **options):
        # Set up Django settings module
        settings_module = settings.SETTINGS_MODULE
        if not settings_module:
            settings_module = 'mysite.settings'  # Replace 'your_project' with the actual name of your Django project
            os.environ.setdefault('DJANGO_SETTINGS_MODULE', settings_module)

        popular_ingredients = [
            'Garlic',
            'Onion',
            'Tomato',
            'Rice',
            'Chicken',
            'Beef',
            'Pork',
            'Fish',
            'Lemon',
            'Olive Oil',
            'Coconut Milk',
            'Ginger',
            'Cilantro',
            'Turmeric',
            'Cumin',
            'Coriander',
            'Chili Pepper',
            'Soy Sauce',
            'Cinnamon',
            'Parmesan Cheese',
            'Basil',
            'Parsley',
            'Cayenne Pepper',
            'Lime',
            'Egg',
            'Butter',
            'Potato',
            'Carrot',
            'Bell Pepper',
            'Cabbage',
            'Mushroom',
            'Shrimp',
            'Salt',
            'Black Pepper',
            'Paprika',
            'Thyme',
            'Rosemary',
            'Oregano',
            'Mustard',
            'Honey',
            'Vinegar',
            'Balsamic Vinegar',
            'Sesame Oil',
            'Red Wine',
            'White Wine',
            'Worcestershire Sauce',
            'Mayonnaise',
            'Yogurt',
            'Milk',
            'Cream',
            'Sour Cream',
            'Cocoa Powder',
            'Vanilla Extract',
            'Maple Syrup',
            'Molasses',
            'Agave Nectar',
            'Brown Sugar',
            'Granulated Sugar',
            'Flour',
            'Baking Powder',
            'Baking Soda',
            'Cornstarch',
            'Bread Crumbs',
            'Oats',
            'Almonds',
            'Walnuts',
            'Peanuts',
            'Cashews',
            'Pecans',
            'Sunflower Seeds',
            'Pumpkin Seeds',
            'Sesame Seeds',
            'Chia Seeds',
            'Quinoa',
            'Barley',
            'Lentils',
            'Chickpeas',
            'Black Beans',
            'Kidney Beans',
            'Cannellini Beans',
            'Coconut',
            'Pineapple',
            'Mango',
            'Banana',
            'Avocado',
            'Strawberries',
            'Blueberries',
            'Raspberries',
            'Blackberries',
            'Cranberries',
            'Orange',
            'Apple',
            'Grapes',
            'Pomegranate',
            'Watermelon',
            'Honeydew Melon',
            'Cantaloupe',
            'Kiwi',
            'Peach',
            'Pear',
            'Plum',
            'Fig',
            'Dates',
            'Prunes',
            'Cucumber',
            'Zucchini',
            'Eggplant',
            'Celery',
            'Spinach',
            'Kale',
            'Lettuce',
            'Arugula',
            'Broccoli',
            'Cauliflower',
            'Asparagus',
            'Artichoke',
            'Green Beans',
            'Peas',
            'Corn',
            'Radish',
            'Scallions',
            'Garbanzo Beans',
            'Feta Cheese',
            'Mozzarella Cheese',
            'Cheddar Cheese',
            'Parmigiano-Reggiano',
            'Gouda Cheese',
            'Goat Cheese',
            'Blue Cheese',
            'Camembert Cheese',
            'Brie Cheese',
            'Cream Cheese',
            'Swiss Cheese',
            'Cottage Cheese',
            'Gruyere Cheese',
            'Ricotta Cheese',
            'Mascarpone Cheese',
            'Provolone Cheese',
            'Sausage',
            'Salami',
            'Bacon',
            'Ham',
            'Pepperoni',
            'Prosciutto',
            'Salmon',
            'Tuna',
            'Cod',
            'Trout',
            'Crab',
            'Lobster',
            'Shallots',
            'Leek',
            'Rhubarb',
            'Squash',
            'Chives',
            'Tarragon',
            'Cardamom',
            'Cloves',
            'Allspice',
            'Nutmeg',
            'Star Anise',
            'Bay Leaf',
            'Mint',
            'Parsnip',
            'Rutabaga',
            'Turnip',
            'Saffron',
            'Dill',
            'Anchovies',
            'Capers',
            'Miso',
            'Wasabi',
            'Tamari',
            'Sake',
            'Mirin',
            'Sherry',
            'Garam Masala',
            'Curry Powder',
            'Sriracha Sauce',
            'Fish Sauce',
            'Pesto',
            'Peanut Butter',
            'Tahini',
            'Poppy Seeds',
            'Ghee',
            'Egg Noodles',
            'Ramen Noodles',
            'Soba Noodles',
            'Couscous',
            'Rice Noodles',
            'Pita Bread',
            'Naan Bread',
            'Tortillas',
            'Baguette',
            'Sourdough Bread',
            'Cilantro',
            'Cactus',
            'Kaffir Lime Leaves',
            'Fish Roe',
            'Pomegranate Molasses',
            'Mace',
            'Ajwain',
            'Fenugreek',
            'Berbere',
            'Sumac',
            'Tamarind',
            'Jackfruit',
            'Black Salt',
            'Tofu',
            'Seitan',
            'Tempeh',
            'Dashi',
            'Udon Noodles',
            'Bok Choy',
            'Lotus Root',
            'Sichuan Pepper',
            'Black Fungus',
            'Sesame Paste',
            'Shiitake Mushrooms',
            'Galangal',
            'Lemongrass',
            'Kaffir Lime',
            'Pandan Leaves',
            'Fish Sauce',
            'Shrimp Paste',
            'Rice Vinegar',
            'Mirin',
            'Sake',
        ]


        for ingredient_name in popular_ingredients:
            Ingredient.objects.create(name=ingredient_name)

        self.stdout.write(self.style.SUCCESS('Successfully populated ingredients.'))
