# Generated by Django 4.2.4 on 2023-08-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
